# templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ index .Values.ingress.tls 0 "certificateName" }}
spec:
  secretName: {{ index .Values.ingress.tls 0 "secretName" }}
  issuerRef:
    name: {{ index .Values.ingress.annotations "cert-manager.io/cluster-issuer" }}-{{ .Values.environment }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.domain }}