apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-certificate
  namespace: {{ .Values.environment }}
spec:
  secretName: {{ .Values.module }}-{{ .Values.environment }}-secret
  issuerRef:
    name: {{ .Values.module }}-{{ .Values.environment }}-issuer  # Make sure this matches your ClusterIssuer name
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  {{- range .Values.services }}
    - {{ .subdomain }}.{{ $.Values.baseDomain }}
  {{- end }}
  commonName: "*.{{ .Values.baseDomain }}"
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
  subject:
    organizations:
      - {{ .Values.module }}