# templates/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ index .Values.ingress.annotations.clusterIssuer }}-{{ .Values.environment }}
  namespace: {{ .Values.environment }}
spec:
  {{- if eq .Values.environment "dev" }}
  selfSigned: {}
  {{- else }}
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.infos.email }}
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.environment }}
    solvers:
      - http01:
          ingress:
            class: nginx
  {{- end }}