# templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ index .Values.ingress.tls 0 "certificateName" }}
  namespace: {{ .Values.environment }}
spec:
  secretName: {{ index .Values.ingress.tls 0 "secretName" }}
  issuerRef:
    name: {{ index .Values.ingress.annotations.clusterIssuer }}-{{ .Values.environment }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.domain }}
  commonName: {{ .Values.domain }}
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth