apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-certificate
  namespace: {{ .Values.environment }}
  labels:
    {{- include "ingress-setup.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.module }}-{{ .Values.environment }}-tls-secret  # Changed secret name
  issuerRef:
    name: {{ .Values.module }}-{{ .Values.environment }}-issuer
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.services }}
    - {{ .subdomain }}.{{ $.Values.baseDomain }}
  {{- end }}
  commonName: "*.{{ .Values.baseDomain }}"
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth