apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "ingress-setup.labels" . | nindent 4 }}
  name: {{ include "ingress-setup.tlsSecretName" . }}
  namespace: {{ .Values.environment }}
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.tls.issuer }}-{{ .Values.environment }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.services }}
    - {{ .subdomain }}.{{ $.Values.baseDomain }}
    {{- end }}
  commonName: "*.{{ .Values.baseDomain }}"  # Wildcard certificate pour tous les sous-domaines
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth