apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-certificate
  namespace: {{ .Values.environment }}
spec:
  secretName: {{ include "ingress-setup.tlsSecretName" . }}  # Use the helper function
  issuerRef:
    name: {{ .Values.tls.issuer }}-{{ .Values.environment }}
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.services }}
    - {{ .subdomain }}.{{ $.Values.baseDomain }}
  {{- end }}
  commonName: "*.{{ .Values.baseDomain }}"
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth