apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-certificate-{{ .Release.Revision }}
  namespace: {{ .Values.environment }}
spec:
  secretName: {{ .Values.module }}-{{ .Values.environment }}-secret-{{ .Release.Revision }}
  issuerRef:
    name: {{ .Values.module }}-{{ .Values.environment }}-issuer-{{ .Release.Revision }}
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.services }}
    - {{ .subdomain }}.{{ $.Values.baseDomain }}
  {{- end }}
  commonName: "*.{{ .Values.baseDomain }}"
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth