# templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ index .Values.ingress.tls 0 "certificateName" }}
spec:
  secretName: {{ index .Values.ingress.tls 0 "secretName" }}
  issuerRef:
    {{- if eq .Values.environment "dev" }}
    name: selfsigned-issuer
    {{- else }}
    name: letsencrypt-prod
    {{- end }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.domain }}