apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quant-cm-ingress
  namespace: {{ .Values.environment }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingressClass }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations.clusterIssuer }}-{{ .Values.environment }}
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.annotations.nginx.sslRedirect }}"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.annotations.nginx.whiteListSourceRange }}
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ index .Values.ingress.tls 0 "secretName" }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          {{- range .Values.ingress.hosts.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: quant-cm-service
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}