apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-ingress
  namespace: {{ .Values.environment }}
  labels:
    {{- include "ingress-setup.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.module }}-{{ .Values.environment }}-issuer
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ .Values.module }}-{{ .Values.environment }}-tls-secret  # Changed secret name
      hosts:
      {{- range .Values.services }}
        - {{ .subdomain }}.{{ $.Values.baseDomain }}
      {{- end }}
  rules:
  {{- range .Values.services }}
    - host: {{ .subdomain }}.{{ $.Values.baseDomain }}
      http:
        paths:
          - path: {{ .service.path }}
            pathType: {{ .service.pathType }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
  {{- end }}