apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-ingress
  namespace: {{ .Values.environment }}
  labels:
    {{- include "ingress-setup.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ include "ingress-setup.tlsSecretName" . }}
      hosts:
        - {{ $.Values.baseDomain }}
  rules:
    - host: {{ $.Values.baseDomain }}
      http:
        paths:
          {{- range .Values.services }}
          - path: {{ .service.path }}
            pathType: {{ .service.pathType }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
          {{- end }}