# templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quant-cm-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ index .Values.ingress.annotations "cert-manager.io/cluster-issuer" }}-{{ .Values.environment }}
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ index .Values.ingress.tls 0 "secretName" }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          {{- range .Values.ingress.hosts.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: quant-cm-service
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}