apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-ingress
  namespace: {{ .Values.environment }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ .Values.tls.secretName }}
      hosts:
        {{- range .Values.services }}
        - {{ .subdomain }}.{{ $.Values.baseDomain }}
        {{- end }}
  rules:
    {{- range .Values.services }}
    - host: {{ .subdomain }}.{{ $.Values.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
    {{- end }}