apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "ingress-setup.labels" . | nindent 4 }}
  name: central-ingress
  namespace: {{ .Values.environment }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    - secretName: {{ .Values.tls.secretName }}
      hosts:
        {{- range .Values.services }}
        - {{ .subdomain }}.{{ $.Values.baseDomain }}
        {{- end }}
  rules:
    {{- range .Values.services }}
    - host: {{ include "ingress-setup.hostname" (dict "subdomain" .subdomain "baseDomain" $.Values.baseDomain) }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
    {{- end }}