apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-proxy
  template:
    metadata:
      labels:
        app: tailscale-proxy
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          env:
            - name: TS_USERSPACE
              value: "true"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_DEST_IP
              valueFrom:
                secretKeyRef:
                  name: tailscale-ip-ingress
                  key: TS_IPINGRESS
            - name: TS_EXTRA_ARGS
              value: "--accept-routes=true --advertise-routes=192.168.68.0/24"
            - name: TS_SOCKET
              value: "/tmp/tailscaled.sock"
            - name: TS_STATE_DIR
              value: "/tmp"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add:
                - NET_ADMIN
          command:
            - /bin/sh
            - -c
            - |
              /usr/local/bin/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
              sleep 5
              /usr/local/bin/tailscale up --authkey="${TS_AUTHKEY}" $TS_EXTRA_ARGS
              /usr/local/bin/tailscale serve --bg http://192.168.68.6:80
              sleep infinity
          livenessProbe:
            httpGet:
              path: /health
              port: 41641
            initialDelaySeconds: 30
            periodSeconds: 60