# templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ts-ip-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  refreshInterval: 1h
  target:
    name: ts-ip-value
  data:
    - secretKey: TS_IP
      remoteRef:
        key: tailscale/ts-secrets
        property: TS_IP

# templates/ipaddresspool.yaml
{{- $pool := index .Values.ipAddressPools .Values.mode }}
# templates/ipaddresspool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $pool.name }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - valueFrom:
        secretKeyRef:
          name: ts-ip-value
          key: TS_IP