# templates/ipaddresspool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPools.name }}
  namespace: {{ .Values.ipAddressPools.namespace }}
spec:
  addresses:
  - valueFrom:
      secretKeyRef:
        name: {{ .Values.ipAddressPools.secretRef.name }}
        namespace: {{ .Values.ipAddressPools.namespace }}
        key: {{ .Values.ipAddressPools.secretRef.key }}