apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.ipAddressPools.namespace }}/metallb-ip-config  # Référence correcte du configmap
  autoAssign: true
