apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPools.name }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{- $configMap := (lookup "v1" "ConfigMap" .Release.Namespace "metallb-ip-config") }}
    {{- if and $configMap $configMap.data.addresses }}
    - {{ $configMap.data.addresses }}
    {{- end }}
  autoAssign: true