# templates/ipaddresspool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tailscale-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  - valueFrom:
      secretKeyRef:
        name: ts-secrets
        namespace: tailscale
        key: TS_IP