apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.68.5-192.168.68.15  # Plage d'IP incluant votre IP Minikube