# templates/ipaddresspool.yaml
{{- $pool := index .Values.ipAddressPools .Values.mode }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $pool.name }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ $pool.secretRef.key }}