apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses: 
   - "127.0.0.1/32"  # Adresse locale # attention pas utilisable mais remplacée par le job
  autoAssign: true
