# templates/ipaddresspool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tailscale-pool
  namespace: default
spec:
  addresses:
    - '{{ `{{ (index (kubectl "get" "secret" "ts-secrets" "-n" "tailscale" "-o" "jsonpath={.data.TS_IP}") 0) | b64dec }}` }}'