# templates/job-init-pool.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: metallb-init-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: metallb-init-config
      containers:
      - name: init-config
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          # Lire l'IP depuis le secret
          IP=$(kubectl get secret -n {{ .Values.ipAddressPools.namespace }} {{ .Values.ipAddressPools.secretRef.name }} -o jsonpath="{.data.{{ .Values.ipAddressPools.secretRef.key }}}" | base64 -d)
          # Stocker l'IP dans un ConfigMap
          kubectl create configmap metallb-ip-config -n {{ .Release.Namespace }} --from-literal=addresses="$IP" || kubectl patch configmap metallb-ip-config -n {{ .Release.Namespace }} --type=merge -p "{\"data\":{\"addresses\":\"$IP\"}}"
      restartPolicy: Never
  backoffLimit: 4