apiVersion: batch/v1
kind: Job
metadata:
  name: metallb-init-config-metallb-config
  namespace: metallb-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: metallb-init-config
    spec:
      serviceAccountName: metallb-init-config
      restartPolicy: Never
      containers:
      - name: init-config
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -xec
        - |
          echo "=== Starting init job at $(date) ==="
          
          # Récupérer l'IP depuis le secret Tailscale
          IP=$(kubectl get secret -n tailscale ts-secrets -o jsonpath="{.data.TS_IP}" | base64 -d)
          echo "IP from secret: $IP"
          
          # Mettre à jour l'IPAddressPool
          kubectl patch ipaddresspool first-pool -n metallb-system --type merge \
            -p "{\"spec\":{\"addresses\":[\"$IP\"]}}"
          
          echo "=== Job completed at $(date) ==="