# templates/job-init-pool.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: metallb-init-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"  # S'exécute après la création du RBAC
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: metallb-init-config
    spec:
      serviceAccountName: metallb-init-config
      containers:
      - name: init-config
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -xec
        - |
          echo "=== Starting init job at $(date) ==="
          kubectl get serviceaccount metallb-init-config
          kubectl auth can-i get secrets -n tailscale
          kubectl auth can-i create configmap -n {{ .Release.Namespace }}
          
          IP=$(kubectl get secret -n tailscale ts-secrets -o jsonpath="{.data.TS_IP}" | base64 -d)
          echo "IP from secret: $IP"
          
          kubectl create configmap metallb-ip-config \
            -n {{ .Release.Namespace }} \
            --from-literal=addresses="$IP" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          echo "=== Job completed at $(date) ==="
      restartPolicy: Never