# templates/l2advertisement.yaml
{{- $pool := index .Values.ipAddressPools .Values.mode }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2Advertisements.name }}
  namespace: {{ $pool.namespace }}
spec:
  ipAddressPools:
  - {{ $pool.name }}