apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-init-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get"]
- apiGroups: ["metallb.io"]  # Ajout des permissions MetalLB
  resources: ["ipaddresspools"]
  verbs: ["get", "patch"]