# templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-init-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-secret-reader
  namespace: {{ .Values.ipAddressPools.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["{{ .Values.ipAddressPools.secretRef.name }}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metallb-secret-reader
  namespace: {{ .Values.ipAddressPools.namespace }}
subjects:
- kind: ServiceAccount
  name: metallb-init-config
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: metallb-secret-reader
  apiGroup: rbac.authorization.k8s.io