# templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-init-config
  namespace: {{ .Release.Namespace }}
---
# Un seul ClusterRole pour toutes les permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-init-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  # Pas de resourceNames pour permettre l'accès cross-namespace
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch", "get"]
---
# Un seul ClusterRoleBinding pour lier le ServiceAccount au ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-init-binding
subjects:
- kind: ServiceAccount
  name: metallb-init-config
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-init-role