# templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-init-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"  # Exécuté avant le Job (-5)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-secret-reader
  namespace: {{ .Values.ipAddressPools.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["{{ .Values.ipAddressPools.secretRef.name }}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metallb-secret-reader
  namespace: {{ .Values.ipAddressPools.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
subjects:
- kind: ServiceAccount
  name: metallb-init-config
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: metallb-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-config-creator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metallb-config-creator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
subjects:
- kind: ServiceAccount
  name: metallb-init-config
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: metallb-config-creator
  apiGroup: rbac.authorization.k8s.io