# values.yaml
namespace: "metallb-system"
ipAddressPools:

  # # standard:
  # name: "first-pool"
  # namespace: "metallb-system"
  # secretRef:
  #   name: "localhost-secrets"
  #   key: "LOCALHOST_IP"

  # tailscale:
  name: "tailscale-pool"
  namespace: "tailescale"
  secretRef:
    name: "ts-secrets"
    key: "TS_IP"
l2Advertisements:
  name: "l2-advertisement"