# values.yaml
ipAddressPools:
  name: "first-pool"
  namespace: "metallb-system"  # Namespace du ConfigMap
  secretRef:
    name: "ts-secrets"         # Nom du secret dans le namespace tailscale
    key: "TS_IP"               # Clé dans le secret

l2Advertisements:
  name: "l2-advertisement"

webhook:
  enabled: true
  serviceAccount:
    create: true
  tls:
    generate: true
