# values.yaml
ipAddressPools:
  name: "first-pool"
  namespace: "tailscale"  # namespace où se trouve le secret
  secretRef:
    name: "ts-secrets"    # nom du secret
    key: "TS_IP"         # clé dans le secret

l2Advertisements:
  name: "l2-advertisement"

webhook:
  enabled: true