# values-prod.yaml
environment: prod
domain: quant-cm.com
infos:
  email: quant-cm@gmail.com
service:
  port: 80
  targetPort: 8070
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    paths:
      - path: /
        pathType: Prefix
  tls:
    - secretName: quant-cm-cert-prod
    - certificateName: quant-cm-cert-prod