# values-prod.yaml
domain: quant-cm.com
infos:
  email: quant-cm@gmail.com
service:
  port: 80
  targetPort: 8070
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: quant-cm-tls-prod
    - certificateName: quant-cm-cert-prod