apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-proxy
  template:
    metadata:
      labels:
        app: tailscale-proxy
    spec:
      serviceAccountName: tailscale
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 8.8.8.8
        searches:
          - tailscale.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      initContainers:
        - name: install-socat
          image: debian:bullseye-slim
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && apt-get install -y socat
              cp $(which socat) /tools/
              ldd $(which socat) | grep readline | cut -d ' ' -f 3 | xargs -I {} cp {} /tools/
          volumeMounts:
            - name: tools
              mountPath: /tools
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp /tools/* /usr/local/lib/
              cp /tools/socat /usr/local/bin/
              ldconfig
              tailscaled --state=kube:ts-secrets &
              sleep 5
              tailscale up --reset \
                --hostname="${TS_HOSTNAME}" \
                --auth-key="${TS_AUTHKEY}" \
                --advertise-routes="${TS_ROUTES}"
              socat TCP4-LISTEN:80,reuseaddr,fork TCP4:${TS_DEST_IP}:80 &
              tailscale serve --bg http://127.0.0.1:80
              sleep infinity
          env:
            - name: TS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_HOSTNAME
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_AUTHKEY
            - name: TS_DEST_IP
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_DEST_IP
            - name: TS_ROUTES
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_ROUTES
          volumeMounts:
            - name: tools
              mountPath: /tools
            - name: tailscale-state
              mountPath: /var/lib/tailscale
          securityContext:
            privileged: true
      volumes:
        - name: tools
          emptyDir: {}
        - name: tailscale-state
          emptyDir: {}