apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-proxy
  template:
    metadata:
      labels:
        app: tailscale-proxy
    spec:
      serviceAccountName: tailscale
      volumes:
        - name: tailscaled-socket
          emptyDir: {}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          env:
            - name: TS_KUBE_SECRET
              value: ts-secrets
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_AUTHKEY
            - name: TS_USERSPACE
              value: "false"
            - name: TS_DEST_IP
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_DEST_IP
            - name: TS_ROUTES
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_ROUTES
            - name: TS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_HOSTNAME
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command:
            - "/bin/sh"
            - "-c"  
            - |
              tailscaled --state=kube:ts-secrets &
              sleep 5
              tailscale up --auth-key=${TS_AUTHKEY} --hostname="${TS_HOSTNAME}" --accept-routes --advertise-routes=${TS_ROUTES}
              tailscale serve --bg http://${TS_DEST_IP}:80
              sleep infinity
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: tailscaled-socket
              mountPath: /tmp
