apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-proxy
  template:
    metadata:
      labels:
        app: tailscale-proxy
    spec:
      serviceAccountName: tailscale
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - tailscale.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              tailscaled --state=mem: --tun=userspace-networking &
              sleep 5
              tailscale up --authkey="${TS_AUTHKEY}" --hostname="${TS_HOSTNAME}"
              tailscale serve --bg --http-handler=proxy http://localhost:8080/
              nc -l -p 8080 -e sh -c 'echo -e "HTTP/1.1 200 OK\n\nHello"'
              sleep infinity
          env:
            - name: TS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_HOSTNAME
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_AUTHKEY
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          livenessProbe:
            httpGet:
              path: /health
              port: 41641
            initialDelaySeconds: 60
            periodSeconds: 60