apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-proxy
  template:
    metadata:
      labels:
        app: tailscale-proxy
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              tailscaled --state=mem:ts-secrets --tun=userspace-networking &
              sleep 5
              tailscale up --authkey="${TS_AUTHKEY}" --hostname="${TS_HOSTNAME}" --accept-routes --advertise-routes="${TS_ROUTES}"
              tailscale serve --bg tcp:4001 tcp://ibgateway.ib-gateway.svc.cluster.local:4001
              tailscale serve --bg tcp:4002 tcp://ibgateway.ib-gateway.svc.cluster.local:4002
              tailscale serve --bg tcp:5900 tcp://ibgateway.ib-gateway.svc.cluster.local:5900
              tailscale serve --bg tcp:6080 tcp://ibgateway-novnc.ib-gateway.svc.cluster.local:6080
              sleep infinity
          env:
            - name: TS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_HOSTNAME
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_AUTHKEY
            - name: TS_ROUTES
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_ROUTES
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
