apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-proxy
  template:
    metadata:
      labels:
        app: tailscale-proxy
    spec:
      serviceAccountName: tailscale
      initContainers:
        - name: install-socat
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - apk add --no-cache socat && cp $(which socat) /tools/
          volumeMounts:
            - name: tools
              mountPath: /tools
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp /tools/socat /usr/local/bin/ && chmod +x /usr/local/bin/socat
              tailscaled --state=kube:ts-secrets &
              sleep 5
              tailscale up --reset \
                --advertise-routes=${TS_ROUTES} \
                --auth-key=${TS_AUTHKEY} \
                --hostname=${TS_HOSTNAME}
              socat TCP4-LISTEN:80,reuseaddr,fork TCP4:${TS_DEST_IP}:80 &
              tailscale serve --bg http://127.0.0.1:80
              sleep infinity
          env:
            - name: TS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_HOSTNAME
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_AUTHKEY
            - name: TS_DEST_IP
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_DEST_IP
            - name: TS_ROUTES
              valueFrom:
                secretKeyRef:
                  name: ts-secrets
                  key: TS_ROUTES
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: tools
              mountPath: /tools
            - name: tailscale-state
              mountPath: /var/lib/tailscale
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: tools
          emptyDir: {}
        - name: tailscale-state
          emptyDir: {}