apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-proxy
  template:
    metadata:
      labels:
        app: tailscale-proxy
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          env:

            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: ts-authkey
                  key: TS_AUTHKEY

            - name: TS_USERSPACE
              value: "false"

            - name: TS_DEST_IP
              valueFrom:
                secretKeyRef:
                  name: ts-dest-ip
                  key: TS_DEST_IP
            
            - name: TS_ROUTES
              valueFrom:
                secretKeyRef:
                  name: ts-routes
                  key: TS_ROUTES

            - name: TS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: ts-hostname
                  key: TS_IPHOSTNAME                  

          securityContext:
            capabilities:
              add:
                - NET_ADMIN


          command:
            - "/bin/sh"
            - "-c"
            - "tailscale up --accept-dns=false --auth-key=${TS_AUTHKEY} --accept-routes --advertise-routes=${TS_ROUTES}"
